remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: Blogpad
description: A simplistic medium style blog WYSIWYG editor for website.
show_downloads: ["true"]
github:
  live_url: https://www.tarunbisht.com/blogpad/live.html
